export const questionsData = {
  superlatives: [
    "Kim guruhda eng ko'p uxlaydi? 😴",
    "Kim birinchi boy (millioner) bo'ladi? 💰",
    "Kim har doim uchrashuvlarga kechikib keladi? ⏰",
    "Kim telefonga eng ko'p mukkasidan ketgan? 📱",
    "Kim eng ko'p ovqat yeydi, lekin semirmaydi? 🍔",
    "Kim birinchi bo'lib uylanadi/turmushga chiqadi? 💍",
    "Kim kutilmaganda kosmonavt bo'lib ketishi mumkin? 🚀",
    "Kim eng yaxshi sirlarni saqlay oladi? 🤫",
    "Kim mashinani eng dabdala haydaydi? 🚗",
    "Kim kulgili hazillar qilish bo'yicha usta? 🎭",
    "Kim kechasi soat 3 da muzlatgichni titadi? 🍕",
    "Kim eng mehmondo'st va saxiy? 🤝",
    "Kim guruhda eng ko'p stiker va gif ishlatadi? 🤪",
    "Kim eng kutilmagan sarguzashtlarga kirishib yuradi? 🎒",
    "Kim eng ko'p qahva (kofe) ichadi? ☕"
  ],
  quiz: [
    {
      category: "💻 Texnologiya",
      question: "Telegram messendjeriga nechanchi yili asos solingan?",
      options: ["2011", "2013", "2015", "2010"],
      answer: 1
    },
    {
      category: "💻 Texnologiya",
      question: "World Wide Web (WWW) konsepsiyasining muallifi kim?",
      options: ["Bill Gates", "Steve Jobs", "Tim Berners-Lee", "Mark Zuckerberg"],
      answer: 2
    },
    {
      category: "💻 Texnologiya",
      question: "Python dasturlash tili muallifi kim?",
      options: ["Guido van Rossum", "James Gosling", "Bjarne Stroustrup", "Linus Torvalds"],
      answer: 0
    },
    {
      category: "📚 Tarix",
      question: "Amir Temur nechanchi yilda tug'ilgan?",
      options: ["1336-yil 9-aprel", "1405-yil 18-fevral", "1370-yil 12-may", "1340-yil 1-sentyabr"],
      answer: 0
    },
    {
      category: "📚 Tarix",
      question: "Alisher Navoiyning mashhur 5 doston majmuasi nima deyiladi?",
      options: ["Devon", "Xamsa", "Lison ut-tayr", "Majolis un-nafois"],
      answer: 1
    },
    {
      category: "⚽ Sport",
      question: "Futbol bo'yicha birinchi jahon chempionati qaysi davlatda o'tkazilgan?",
      options: ["Braziliya", "Urugvay", "Angliya", "Italiya"],
      answer: 1
    },
    {
      category: "⚽ Sport",
      question: "Olimpiada o'yinlarining ramzidagi 5 ta halqa nimani anglatadi?",
      options: ["5 ta okean", "5 ta qit'a", "5 ta element", "5 ta asosiy sport turi"],
      answer: 1
    },
    {
      category: "🌍 Geografiya",
      question: "Dunyo bo'yicha maydoni eng katta ko'l qaysi?",
      options: ["Baykal", "Kaspiy dengizi", "Viktoriya", "Yuqori ko'l"],
      answer: 1
    },
    {
      category: "🌍 Geografiya",
      question: "O'zbekiston nechta davlat bilan chegaradosh?",
      options: ["4 ta", "5 ta", "6 ta", "7 ta"],
      answer: 1
    },
    {
      category: "🎬 Kino va San'at",
      question: "\"O'tkan kunlar\" filmi rejissori kim?",
      options: ["Shuhrat Abbosov", "Yo'ldosh A'zamov", "Melis Abzalov", "Ali Hamroyev"],
      answer: 1
    },
    {
      category: "🧠 Umumiy Bilim",
      question: "Inson tanasida eng katta organ qaysi?",
      options: ["Jigar", "Yurak", "Teri", "O'pka"],
      answer: 2
    },
    {
      category: "🧠 Umumiy Bilim",
      question: "Qaysi sayyora Qizil sayyora deb ataladi?",
      options: ["Venera", "Mars", "Yupiter", "Saturn"],
      answer: 1
    }
  ],
  fibbage: [
    {
      question: "Qaysi davlatda sigirni haqorat qilish rasman qonunan man etilgan va jarima solinadi?",
      realAnswer: "Hindiston"
    },
    {
      question: "O'zbekistonda eng uzundan-uzun tarixiy ko'chalardan biri hisoblangan Farg'ona yo'li ko'chasi ilgari nima deb atalgan?",
      realAnswer: "Kuybishev shossesi"
    },
    {
      question: "Dunyoda birinchi marotaba poyezdda chekishni taqiqlagan davlat qaysi?",
      realAnswer: "Germaniya"
    },
    {
      question: "Kenguru hayvonining nomi mahalliy avstraliyaliklar tilida Aslida nima ma'noni anglatadi?",
      realAnswer: "Men seni tushunmayapman"
    },
    {
      question: "Kosmosda eng birinchi bo'lib tayyorlangan va yeyilgan ovqat qaysi edi?",
      realAnswer: "Shokoladli sous va go'shtli pyure"
    }
  ],
  alias: [
    "Toshkent", "Somsa", "Telegram", "Futbol", "Muzqaymoq",
    "Harry Potter", "Titanik", "Stomatolog", "Dasturchi", "Taksi driver",
    "Muzlatgich", "Mikrovolnovka", "Telefon quvvatlagich", "Selfi stick",
    "Noutbuk", "Plov (Palov)", "Samarqand", "Chorvoq", "Metropoliten", "Beshbarmak"
  ],
  wordle: [
    "KITOB", "QALAM", "SHAHAR", "VOTAN", "BULOQ",
    "DARAX", "INSON", "ZUKKO", "DARYO", "SHAKAR",
    "QOVUN", "OLMA", "QUYOSH", "SHAHR", "DUNYO",
    "MAKTAB", "OSMON", "KINO", "MEVA", "QISHLOK"
  ],
  spyfallLocations: [
    "✈️ Aeroport", "🏥 Shifoxona", "🏫 Maktab", "🍽 Restoran",
    "🎬 Kinoteatr", "🚂 Poezd vokzali", "🏨 Mehmonxona", "⚽ Stadion",
    "🛳 Kruiz kemasi", "🏖 Plyaj", "🎪 Sirk", "🏛 Muzey"
  ],
  crocodile: [
    "📱 Smartfon quvvatlagichi", "🍕 Kechasi ovqatlanayotgan odam",
    "🚗 Yo'ldagi probka", "🎮 Dasturchi kod yozmoqda",
    "😴 Ma'ruzada uxlab qolgan talaba", "🏃‍♂️ Avtobus ortidan yugurayotgan odam",
    "📸 Selfi tushayotgan sayyoh", "☕ Ertalabki issiq kofe"
  ],
  flags: [
    { flag: "🇦🇫", country: "Afg'oniston", options: ["Afg'oniston", "Antigua va Barbuda", "Madagaskar", "Kongo"], answer: 0 },
    { flag: "🇦🇱", country: "Albaniya", options: ["Kipr", "Kiribati", "Armaniston", "Albaniya"], answer: 3 },
    { flag: "🇩🇿", country: "Jazoir", options: ["Vatikan", "Kamerun", "Jazoir", "Madagaskar"], answer: 2 },
    { flag: "🇦🇩", country: "Andorra", options: ["Madagaskar", "Gana", "Andorra", "Serra-Leone"], answer: 2 },
    { flag: "🇦🇴", country: "Angola", options: ["Angola", "Boliviya", "Armaniston", "Lyuksemburg"], answer: 0 },
    { flag: "🇦🇬", country: "Antigua va Barbuda", options: ["Chexiya", "Shimoliy Koreya", "Antigua va Barbuda", "Ekvatorial Gvineya"], answer: 2 },
    { flag: "🇦🇷", country: "Argentina", options: ["Dominikan Respublikasi", "Tonga", "Tailand", "Argentina"], answer: 3 },
    { flag: "🇦🇲", country: "Armaniston", options: ["Belgiya", "Samoa", "Nauru", "Armaniston"], answer: 3 },
    { flag: "🇦🇺", country: "Avstraliya", options: ["Avstraliya", "Lyuksemburg", "Tanzaniya", "Ekvador"], answer: 0 },
    { flag: "🇦🇹", country: "Avstriya", options: ["Burundi", "Liberiya", "Laos", "Avstriya"], answer: 3 },
    { flag: "🇦🇿", country: "Ozarbayjon", options: ["Ozarbayjon", "Benin", "Kiribati", "Tanzaniya"], answer: 0 },
    { flag: "🇧🇸", country: "Bagama orollari", options: ["Vanuatu", "Bagama orollari", "Esvatini", "Keniya"], answer: 1 },
    { flag: "🇧🇭", country: "Bahrayn", options: ["Bahrayn", "Botsvana", "Palau", "Shimoliy Makedoniya"], answer: 0 },
    { flag: "🇧🇩", country: "Bangladesh", options: ["Seyshel orollari", "Ukraina", "Esvatini", "Bangladesh"], answer: 3 },
    { flag: "🇧🇧", country: "Barbados", options: ["Gonduras", "Bahrayn", "Barbados", "Panama"], answer: 2 },
    { flag: "🇧🇾", country: "Belarus", options: ["Markaziy Afrika Respublikasi", "Belarus", "Somali", "Namibiya"], answer: 1 },
    { flag: "🇧🇪", country: "Belgiya", options: ["Belgiya", "Mavrikiy", "Kiribati", "Sudan"], answer: 0 },
    { flag: "🇧🇿", country: "Beliz", options: ["Sloveniya", "Portugaliya", "Beliz", "Malavi"], answer: 2 },
    { flag: "🇧🇯", country: "Benin", options: ["Avstraliya", "Shveytsariya", "Benin", "Malta"], answer: 2 },
    { flag: "🇧🇹", country: "Butan", options: ["Daniya", "Butan", "Litva", "Kambodja"], answer: 1 },
    { flag: "🇧🇴", country: "Boliviya", options: ["Kamerun", "Burkina-Faso", "Boliviya", "Gayana"], answer: 2 },
    { flag: "🇧🇦", country: "Bosniya va Gertsegovina", options: ["Bosniya va Gertsegovina", "Qatar", "Sudan", "Shvetsiya"], answer: 0 },
    { flag: "🇧🇼", country: "Botsvana", options: ["Urugvay", "Botsvana", "Shvetsiya", "Lixtenshteyn"], answer: 1 },
    { flag: "🇧🇷", country: "Braziliya", options: ["Slovakiya", "Braziliya", "Ispaniya", "Gvatemala"], answer: 1 },
    { flag: "🇧🇳", country: "Bruney", options: ["Urugvay", "Bruney", "Namibiya", "Kuba"], answer: 1 },
    { flag: "🇧🇬", country: "Bolgariya", options: ["Bolgariya", "Maldiv orollari", "Marokash", "Pokiston"], answer: 0 },
    { flag: "🇧🇫", country: "Burkina-Faso", options: ["Burkina-Faso", "Avstraliya", "Dominikan Respublikasi", "Ruminiya"], answer: 0 },
    { flag: "🇧🇮", country: "Burundi", options: ["Kongo DR", "Kabo-Verde", "Burundi", "Saudiya Arabistoni"], answer: 2 },
    { flag: "🇨🇻", country: "Kabo-Verde", options: ["BAA", "Xorvatiya", "Kabo-Verde", "Nepal"], answer: 2 },
    { flag: "🇰🇭", country: "Kambodja", options: ["Armaniston", "Vanuatu", "Kambodja", "Liberiya"], answer: 2 },
    { flag: "🇨🇲", country: "Kamerun", options: ["Kamerun", "Estoniya", "Laos", "Pokiston"], answer: 0 },
    { flag: "🇨🇦", country: "Kanada", options: ["Kanada", "Andorra", "Panama", "Keniya"], answer: 0 },
    { flag: "🇨🇫", country: "Markaziy Afrika Respublikasi", options: ["Bahrayn", "Kambodja", "Markaziy Afrika Respublikasi", "Irlandiya"], answer: 2 },
    { flag: "🇹🇩", country: "Chad", options: ["Senegal", "Chad", "Palau", "Efiopiya"], answer: 1 },
    { flag: "🇨🇱", country: "Chili", options: ["Chili", "Jazoir", "Kot-d'Ivuar", "Venesuela"], answer: 0 },
    { flag: "🇨🇳", country: "Xitoy", options: ["Xitoy", "Filippin", "Peru", "Bruney"], answer: 0 },
    { flag: "🇨🇴", country: "Kolumbiya", options: ["Samoa", "Kolumbiya", "Hindiston", "Ummon"], answer: 1 },
    { flag: "🇰🇲", country: "Komor orollari", options: ["Surinam", "Kipr", "Komor orollari", "Xitoy"], answer: 2 },
    { flag: "🇨🇬", country: "Kongo", options: ["Gruziya", "Kongo", "Sent-Lyusiya", "Marshall orollari"], answer: 1 },
    { flag: "🇨🇩", country: "Kongo DR", options: ["BAA", "Afg'oniston", "Kambodja", "Kongo DR"], answer: 3 },
    { flag: "🇨🇷", country: "Kosta-Rika", options: ["Buyuk Britaniya", "Singapur", "Kosta-Rika", "Gaiti"], answer: 2 },
    { flag: "🇨🇮", country: "Kot-d'Ivuar", options: ["Gambiya", "Kongo DR", "Kot-d'Ivuar", "Maldiv orollari"], answer: 2 },
    { flag: "🇭🇷", country: "Xorvatiya", options: ["Liviya", "Xorvatiya", "Somali", "BAA"], answer: 1 },
    { flag: "🇨🇺", country: "Kuba", options: ["Kuba", "Avstriya", "Isroil", "Mavrikiy"], answer: 0 },
    { flag: "🇨🇾", country: "Kipr", options: ["Qozog'iston", "Chad", "Kipr", "Kosta-Rika"], answer: 2 },
    { flag: "🇨🇿", country: "Chexiya", options: ["Kosta-Rika", "Kiribati", "Turkiya", "Chexiya"], answer: 3 },
    { flag: "🇩🇰", country: "Daniya", options: ["Moldova", "Liberiya", "Kolumbiya", "Daniya"], answer: 3 },
    { flag: "🇩🇯", country: "Jibuti", options: ["Qozog'iston", "Jibuti", "Liviya", "Kot-d'Ivuar"], answer: 1 },
    { flag: "🇩🇲", country: "Dominika", options: ["Eron", "Portugaliya", "Venesuela", "Dominika"], answer: 3 },
    { flag: "🇩🇴", country: "Dominikan Respublikasi", options: ["Kanada", "Dominikan Respublikasi", "Mikroneziya", "Tunis"], answer: 1 },
    { flag: "🇪🇨", country: "Ekvador", options: ["Latviya", "Ekvador", "Liviya", "Tayvan"], answer: 1 },
    { flag: "🇪🇬", country: "Misr", options: ["Misr", "Sent-Kits va Nevis", "Isroil", "Islandiya"], answer: 0 },
    { flag: "🇸🇻", country: "Salvador", options: ["Salvador", "Gvatemala", "Italiya", "Lixtenshteyn"], answer: 0 },
    { flag: "🇬🇶", country: "Ekvatorial Gvineya", options: ["Vengriya", "Sloveniya", "Xorvatiya", "Ekvatorial Gvineya"], answer: 3 },
    { flag: "🇪🇷", country: "Eritreya", options: ["Meksika", "Beliz", "Eritreya", "Papua-Yangi Gvineya"], answer: 2 },
    { flag: "🇪🇪", country: "Estoniya", options: ["Eritreya", "BAA", "Shveytsariya", "Estoniya"], answer: 3 },
    { flag: "🇸🇿", country: "Esvatini", options: ["Esvatini", "Paragvay", "Tuvalu", "Qirg'iziston"], answer: 0 },
    { flag: "🇪🇹", country: "Efiopiya", options: ["Lixtenshteyn", "Polsha", "Maldiv orollari", "Efiopiya"], answer: 3 },
    { flag: "🇫🇯", country: "Fiji", options: ["Bahrayn", "Mongoliya", "Fiji", "Madagaskar"], answer: 2 },
    { flag: "🇫🇮", country: "Finlyandiya", options: ["Ozarbayjon", "Finlyandiya", "Rossiya", "Germaniya"], answer: 1 },
    { flag: "🇫🇷", country: "Fransiya", options: ["Papua-Yangi Gvineya", "Myanma", "Botsvana", "Fransiya"], answer: 3 },
    { flag: "🇬🇦", country: "Gabon", options: ["Gabon", "Yaponiya", "Buyuk Britaniya", "Turkiya"], answer: 0 },
    { flag: "🇬🇲", country: "Gambiya", options: ["BAA", "Kamerun", "Gambiya", "Gvatemala"], answer: 2 },
    { flag: "🇬🇪", country: "Gruziya", options: ["Tanzaniya", "Fransiya", "Gruziya", "Bruney"], answer: 2 },
    { flag: "🇩🇪", country: "Germaniya", options: ["Janubiy Sudan", "Germaniya", "Janubiy Koreya", "Zimbabve"], answer: 1 },
    { flag: "🇬🇭", country: "Gana", options: ["Chexiya", "Gana", "Shvetsiya", "Mongoliya"], answer: 1 },
    { flag: "🇬🇷", country: "Gretsiya", options: ["Singapur", "Yangi Zelandiya", "Zambiya", "Gretsiya"], answer: 3 },
    { flag: "🇬🇩", country: "Grenada", options: ["Iordaniya", "Grenada", "Panama", "Janubiy Koreya"], answer: 1 },
    { flag: "🇬🇹", country: "Gvatemala", options: ["Paragvay", "Ozarbayjon", "Gvatemala", "Senegal"], answer: 2 },
    { flag: "🇬🇳", country: "Gvineya", options: ["Lesoto", "Ruminiya", "Gvineya", "Argentina"], answer: 2 },
    { flag: "🇬🇼", country: "Gvineya-Bisau", options: ["Gvineya-Bisau", "Singapur", "Rossiya", "Latviya"], answer: 0 },
    { flag: "🇬🇾", country: "Gayana", options: ["Gayana", "Namibiya", "Kosta-Rika", "Ekvatorial Gvineya"], answer: 0 },
    { flag: "🇭🇹", country: "Gaiti", options: ["Gaiti", "Moldova", "Polsha", "Sent-Vinsent va Grenadinlar"], answer: 0 },
    { flag: "🇭🇳", country: "Gonduras", options: ["Armaniston", "Fiji", "Zimbabve", "Gonduras"], answer: 3 },
    { flag: "🇭🇺", country: "Vengriya", options: ["Solomon orollari", "Mali", "Vengriya", "Esvatini"], answer: 2 },
    { flag: "🇮🇸", country: "Islandiya", options: ["Surinam", "Sent-Lyusiya", "Islandiya", "Tanzaniya"], answer: 2 },
    { flag: "🇮🇳", country: "Hindiston", options: ["Norvegiya", "Samoa", "Armaniston", "Hindiston"], answer: 3 },
    { flag: "🇮🇩", country: "Indoneziya", options: ["Indoneziya", "Turkmaniston", "Filippin", "Kuba"], answer: 0 },
    { flag: "🇮🇷", country: "Eron", options: ["Albaniya", "Eron", "Bruney", "Gana"], answer: 1 },
    { flag: "🇮🇶", country: "Iroq", options: ["Gambiya", "Yaponiya", "Iroq", "Lyuksemburg"], answer: 2 },
    { flag: "🇮🇪", country: "Irlandiya", options: ["Vatikan", "Irlandiya", "Tojikiston", "Kiribati"], answer: 1 },
    { flag: "🇮🇱", country: "Isroil", options: ["Monako", "Togo", "Isroil", "Laos"], answer: 2 },
    { flag: "🇮🇹", country: "Italiya", options: ["Sudan", "Lesoto", "Bagama orollari", "Italiya"], answer: 3 },
    { flag: "🇯🇲", country: "Yamayka", options: ["Latviya", "Xorvatiya", "Yamayka", "Belgiya"], answer: 2 },
    { flag: "🇯🇵", country: "Yaponiya", options: ["Germaniya", "Yaponiya", "Ruminiya", "Belgiya"], answer: 1 },
    { flag: "🇯🇴", country: "Iordaniya", options: ["Botsvana", "Kamerun", "Liviya", "Iordaniya"], answer: 3 },
    { flag: "🇰🇿", country: "Qozog'iston", options: ["Qozog'iston", "Kipr", "Singapur", "Filippin"], answer: 0 },
    { flag: "🇰🇪", country: "Keniya", options: ["Kabo-Verde", "Keniya", "Sent-Lyusiya", "Polsha"], answer: 1 },
    { flag: "🇰🇮", country: "Kiribati", options: ["Kiribati", "Gvineya-Bisau", "Gvineya", "Rossiya"], answer: 0 },
    { flag: "🇰🇼", country: "Quvayt", options: ["Quvayt", "Marokash", "Esvatini", "Litva"], answer: 0 },
    { flag: "🇰🇬", country: "Qirg'iziston", options: ["Qirg'iziston", "Angola", "Vatikan", "Marokash"], answer: 0 },
    { flag: "🇱🇦", country: "Laos", options: ["Samoa", "Kolumbiya", "Laos", "Fiji"], answer: 2 },
    { flag: "🇱🇻", country: "Latviya", options: ["Latviya", "O'zbekiston", "Shvetsiya", "Portugaliya"], answer: 0 },
    { flag: "🇱🇧", country: "Livan", options: ["Braziliya", "Beliz", "Livan", "Tayvan"], answer: 2 },
    { flag: "🇱🇸", country: "Lesoto", options: ["Komor orollari", "Lesoto", "Daniya", "Tojikiston"], answer: 1 },
    { flag: "🇱🇷", country: "Liberiya", options: ["Yangi Zelandiya", "Gvineya-Bisau", "Liberiya", "Janubiy Sudan"], answer: 2 },
    { flag: "🇱🇾", country: "Liviya", options: ["Liviya", "Seyshel orollari", "Avstriya", "Suriya"], answer: 0 },
    { flag: "🇱🇮", country: "Lixtenshteyn", options: ["Myanma", "Lixtenshteyn", "Moldova", "Ispaniya"], answer: 1 },
    { flag: "🇱🇹", country: "Litva", options: ["Litva", "Lesoto", "Paragvay", "Kongo DR"], answer: 0 },
    { flag: "🇱🇺", country: "Lyuksemburg", options: ["Monako", "Tojikiston", "Efiopiya", "Lyuksemburg"], answer: 3 },
    { flag: "🇲🇬", country: "Madagaskar", options: ["Benin", "Chad", "Madagaskar", "Kabo-Verde"], answer: 2 },
    { flag: "🇲🇼", country: "Malavi", options: ["Malayziya", "AQSH", "Malavi", "Markaziy Afrika Respublikasi"], answer: 2 },
    { flag: "🇲🇾", country: "Malayziya", options: ["Surinam", "Papua-Yangi Gvineya", "Malayziya", "Tanzaniya"], answer: 2 },
    { flag: "🇲🇻", country: "Maldiv orollari", options: ["Gabon", "Gana", "Maldiv orollari", "BAA"], answer: 2 },
    { flag: "🇲🇱", country: "Mali", options: ["Mali", "Ozarbayjon", "Kot-d'Ivuar", "Zimbabve"], answer: 0 },
    { flag: "🇲🇹", country: "Malta", options: ["Malta", "Gaiti", "Bolgariya", "Kambodja"], answer: 0 },
    { flag: "🇲🇭", country: "Marshall orollari", options: ["Sloveniya", "Kanada", "Marshall orollari", "Kongo DR"], answer: 2 },
    { flag: "🇲🇷", country: "Mavritaniya", options: ["Chexiya", "Chili", "Avstraliya", "Mavritaniya"], answer: 3 },
    { flag: "🇲🇺", country: "Mavrikiy", options: ["Kipr", "Samoa", "Chad", "Mavrikiy"], answer: 3 },
    { flag: "🇲🇽", country: "Meksika", options: ["San-Marino", "Meksika", "O'zbekiston", "Gayana"], answer: 1 },
    { flag: "🇫🇲", country: "Mikroneziya", options: ["Ekvatorial Gvineya", "Mikroneziya", "Misr", "Solomon orollari"], answer: 1 },
    { flag: "🇲🇩", country: "Moldova", options: ["BAA", "Moldova", "Hindiston", "Shimoliy Koreya"], answer: 1 },
    { flag: "🇲🇨", country: "Monako", options: ["Monako", "Polsha", "Panama", "Kolumbiya"], answer: 0 },
    { flag: "🇲🇳", country: "Mongoliya", options: ["Gretsiya", "Mongoliya", "Pokiston", "Meksika"], answer: 1 },
    { flag: "🇲🇪", country: "Chernogoriya", options: ["Yangi Zelandiya", "Janubiy Afrika", "Chernogoriya", "Kipr"], answer: 2 },
    { flag: "🇲🇦", country: "Marokash", options: ["Marokash", "Tuvalu", "Tanzaniya", "Albaniya"], answer: 0 },
    { flag: "🇲🇿", country: "Mozambik", options: ["Jazoir", "Butan", "Mozambik", "Lixtenshteyn"], answer: 2 },
    { flag: "🇲🇲", country: "Myanma", options: ["Turkiya", "Myanma", "Litva", "Bosniya va Gertsegovina"], answer: 1 },
    { flag: "🇳🇦", country: "Namibiya", options: ["Gaiti", "Namibiya", "Kolumbiya", "Dominikan Respublikasi"], answer: 1 },
    { flag: "🇳🇷", country: "Nauru", options: ["Braziliya", "Turkiya", "Polsha", "Nauru"], answer: 3 },
    { flag: "🇳🇵", country: "Nepal", options: ["Quvayt", "Botsvana", "Togo", "Nepal"], answer: 3 },
    { flag: "🇳🇱", country: "Niderlandiya", options: ["Niderlandiya", "Mali", "Gayana", "Qatar"], answer: 0 },
    { flag: "🇳🇿", country: "Yangi Zelandiya", options: ["Ekvador", "Fransiya", "Yangi Zelandiya", "Ruminiya"], answer: 2 },
    { flag: "🇳🇮", country: "Nikaragua", options: ["Esvatini", "Nikaragua", "Ruminiya", "Litva"], answer: 1 },
    { flag: "🇳🇪", country: "Niger", options: ["Niger", "Ozarbayjon", "Bolgariya", "Yaponiya"], answer: 0 },
    { flag: "🇳🇬", country: "Nigeriya", options: ["Shri-Lanka", "Argentina", "Senegal", "Nigeriya"], answer: 3 },
    { flag: "🇰🇵", country: "Shimoliy Koreya", options: ["Lixtenshteyn", "Kuba", "Kolumbiya", "Shimoliy Koreya"], answer: 3 },
    { flag: "🇲🇰", country: "Shimoliy Makedoniya", options: ["Shimoliy Makedoniya", "Jibuti", "Gabon", "Somali"], answer: 0 },
    { flag: "🇳🇴", country: "Norvegiya", options: ["Ekvatorial Gvineya", "Norvegiya", "Gabon", "Mavrikiy"], answer: 1 },
    { flag: "🇴🇲", country: "Ummon", options: ["Ummon", "Tonga", "Monako", "Liberiya"], answer: 0 },
    { flag: "🇵🇰", country: "Pokiston", options: ["Jibuti", "Pokiston", "Braziliya", "Niderlandiya"], answer: 1 },
    { flag: "🇵🇼", country: "Palau", options: ["Litva", "Palau", "Jazoir", "Kongo DR"], answer: 1 },
    { flag: "🇵🇦", country: "Panama", options: ["Singapur", "Panama", "Laos", "Janubiy Sudan"], answer: 1 },
    { flag: "🇵🇬", country: "Papua-Yangi Gvineya", options: ["Papua-Yangi Gvineya", "Malavi", "Xitoy", "Tayvan"], answer: 0 },
    { flag: "🇵🇾", country: "Paragvay", options: ["Kiribati", "Paragvay", "Tailand", "O'zbekiston"], answer: 1 },
    { flag: "🇵🇪", country: "Peru", options: ["Chexiya", "Gayana", "Peru", "Turkiya"], answer: 2 },
    { flag: "🇵🇭", country: "Filippin", options: ["Filippin", "Niderlandiya", "Moldova", "Lyuksemburg"], answer: 0 },
    { flag: "🇵🇱", country: "Polsha", options: ["Polsha", "Chernogoriya", "Yaponiya", "Bruney"], answer: 0 },
    { flag: "🇵🇹", country: "Portugaliya", options: ["Marshall orollari", "San-Marino", "AQSH", "Portugaliya"], answer: 3 },
    { flag: "🇶🇦", country: "Qatar", options: ["Qatar", "Daniya", "Kipr", "Gonduras"], answer: 0 },
    { flag: "🇷🇴", country: "Ruminiya", options: ["Shri-Lanka", "Ruminiya", "Serra-Leone", "Mavritaniya"], answer: 1 },
    { flag: "🇷🇺", country: "Rossiya", options: ["Rossiya", "Efiopiya", "Isroil", "Iordaniya"], answer: 0 },
    { flag: "🇷🇼", country: "Ruanda", options: ["Serbiya", "Bosniya va Gertsegovina", "Kamerun", "Ruanda"], answer: 3 },
    { flag: "🇰🇳", country: "Sent-Kits va Nevis", options: ["Afg'oniston", "Slovakiya", "Sent-Kits va Nevis", "Latviya"], answer: 2 },
    { flag: "🇱🇨", country: "Sent-Lyusiya", options: ["Fransiya", "Suriya", "Sent-Lyusiya", "Myanma"], answer: 2 },
    { flag: "🇻🇨", country: "Sent-Vinsent va Grenadinlar", options: ["Jazoir", "Sent-Kits va Nevis", "Sent-Vinsent va Grenadinlar", "Hindiston"], answer: 2 },
    { flag: "🇼🇸", country: "Samoa", options: ["Argentina", "Dominika", "Sent-Kits va Nevis", "Samoa"], answer: 3 },
    { flag: "🇸🇲", country: "San-Marino", options: ["Trinidad va Tobago", "San-Marino", "Irlandiya", "Eritreya"], answer: 1 },
    { flag: "🇸🇹", country: "San-Tome va Prinsipi", options: ["San-Tome va Prinsipi", "AQSH", "Chili", "Lesoto"], answer: 0 },
    { flag: "🇸🇦", country: "Saudiya Arabistoni", options: ["Latviya", "Gruziya", "Liviya", "Saudiya Arabistoni"], answer: 3 },
    { flag: "🇸🇳", country: "Senegal", options: ["Sloveniya", "Niderlandiya", "Shimoliy Makedoniya", "Senegal"], answer: 3 },
    { flag: "🇷🇸", country: "Serbiya", options: ["Serbiya", "Iordaniya", "Bruney", "Kabo-Verde"], answer: 0 },
    { flag: "🇸🇨", country: "Seyshel orollari", options: ["Eritreya", "Filippin", "Burkina-Faso", "Seyshel orollari"], answer: 3 },
    { flag: "🇸🇱", country: "Serra-Leone", options: ["Komor orollari", "Malayziya", "Qatar", "Serra-Leone"], answer: 3 },
    { flag: "🇸🇬", country: "Singapur", options: ["Avstriya", "Yaman", "Shvetsiya", "Singapur"], answer: 3 },
    { flag: "🇸🇰", country: "Slovakiya", options: ["Chili", "Somali", "Paragvay", "Slovakiya"], answer: 3 },
    { flag: "🇸🇮", country: "Sloveniya", options: ["Sloveniya", "Kongo DR", "Yaponiya", "Senegal"], answer: 0 },
    { flag: "🇸🇧", country: "Solomon orollari", options: ["Litva", "Liviya", "Nikaragua", "Solomon orollari"], answer: 3 },
    { flag: "🇸🇴", country: "Somali", options: ["Somali", "Yangi Zelandiya", "Moldova", "Burkina-Faso"], answer: 0 },
    { flag: "🇿🇦", country: "Janubiy Afrika", options: ["Burkina-Faso", "Janubiy Afrika", "Zimbabve", "Kambodja"], answer: 1 },
    { flag: "🇰🇷", country: "Janubiy Koreya", options: ["Shimoliy Makedoniya", "Janubiy Koreya", "Grenada", "Armaniston"], answer: 1 },
    { flag: "🇸🇸", country: "Janubiy Sudan", options: ["Sudan", "O'zbekiston", "Janubiy Sudan", "Irlandiya"], answer: 2 },
    { flag: "🇪🇸", country: "Ispaniya", options: ["Butan", "Ispaniya", "Lixtenshteyn", "Turkmaniston"], answer: 1 },
    { flag: "🇱🇰", country: "Shri-Lanka", options: ["Zimbabve", "Venesuela", "Gayana", "Shri-Lanka"], answer: 3 },
    { flag: "🇸🇩", country: "Sudan", options: ["Gayana", "Sudan", "Keniya", "Turkiya"], answer: 1 },
    { flag: "🇸🇷", country: "Surinam", options: ["Meksika", "Surinam", "Sent-Kits va Nevis", "Braziliya"], answer: 1 },
    { flag: "🇸🇪", country: "Shvetsiya", options: ["Esvatini", "Marokash", "Turkmaniston", "Shvetsiya"], answer: 3 },
    { flag: "🇨🇭", country: "Shveytsariya", options: ["Braziliya", "Shveytsariya", "Mavrikiy", "Qozog'iston"], answer: 1 },
    { flag: "🇸🇾", country: "Suriya", options: ["Jazoir", "Barbados", "Tonga", "Suriya"], answer: 3 },
    { flag: "🇹🇼", country: "Tayvan", options: ["Urugvay", "Tayvan", "Burkina-Faso", "Kolumbiya"], answer: 1 },
    { flag: "🇹🇯", country: "Tojikiston", options: ["San-Tome va Prinsipi", "Barbados", "Tojikiston", "Belarus"], answer: 2 },
    { flag: "🇹🇿", country: "Tanzaniya", options: ["Livan", "Bahrayn", "Tanzaniya", "Iordaniya"], answer: 2 },
    { flag: "🇹🇭", country: "Tailand", options: ["Urugvay", "Fiji", "Kipr", "Tailand"], answer: 3 },
    { flag: "🇹🇱", country: "Sharqiy Timor", options: ["Shveytsariya", "Sharqiy Timor", "Chad", "Gvatemala"], answer: 1 },
    { flag: "🇹🇬", country: "Togo", options: ["Albaniya", "Burkina-Faso", "Togo", "Mozambik"], answer: 2 },
    { flag: "🇹🇴", country: "Tonga", options: ["Sent-Kits va Nevis", "Yaman", "Tonga", "Sharqiy Timor"], answer: 2 },
    { flag: "🇹🇹", country: "Trinidad va Tobago", options: ["Trinidad va Tobago", "Gaiti", "Yaponiya", "Isroil"], answer: 0 },
    { flag: "🇹🇳", country: "Tunis", options: ["Tunis", "Bruney", "Zambiya", "Malayziya"], answer: 0 },
    { flag: "🇹🇷", country: "Turkiya", options: ["Niderlandiya", "Braziliya", "Turkiya", "Botsvana"], answer: 2 },
    { flag: "🇹🇲", country: "Turkmaniston", options: ["Fiji", "Mavrikiy", "Turkmaniston", "Avstraliya"], answer: 2 },
    { flag: "🇹🇻", country: "Tuvalu", options: ["Polsha", "Turkmaniston", "Tuvalu", "Kosta-Rika"], answer: 2 },
    { flag: "🇺🇬", country: "Uganda", options: ["Malayziya", "Ruanda", "Uganda", "Mavrikiy"], answer: 2 },
    { flag: "🇺🇦", country: "Ukraina", options: ["Italiya", "Misr", "Barbados", "Ukraina"], answer: 3 },
    { flag: "🇦🇪", country: "BAA", options: ["Janubiy Koreya", "Dominika", "BAA", "Meksika"], answer: 2 },
    { flag: "🇬🇧", country: "Buyuk Britaniya", options: ["Zimbabve", "Buyuk Britaniya", "Dominikan Respublikasi", "Norvegiya"], answer: 1 },
    { flag: "🇺🇸", country: "AQSH", options: ["AQSH", "Boliviya", "Vanuatu", "Xitoy"], answer: 0 },
    { flag: "🇺🇾", country: "Urugvay", options: ["Ekvador", "Fiji", "Ruminiya", "Urugvay"], answer: 3 },
    { flag: "🇺🇿", country: "O'zbekiston", options: ["Gruziya", "O'zbekiston", "Meksika", "Ispaniya"], answer: 1 },
    { flag: "🇻🇺", country: "Vanuatu", options: ["Kuba", "Chernogoriya", "Vanuatu", "Kanada"], answer: 2 },
    { flag: "🇻🇦", country: "Vatikan", options: ["San-Marino", "Sent-Kits va Nevis", "Vatikan", "Lesoto"], answer: 2 },
    { flag: "🇻🇪", country: "Venesuela", options: ["Venesuela", "Malayziya", "Kosta-Rika", "Boliviya"], answer: 0 },
    { flag: "🇻🇳", country: "Vyetnam", options: ["Vyetnam", "Yamayka", "Marshall orollari", "Belarus"], answer: 0 },
    { flag: "🇾🇪", country: "Yaman", options: ["Yaman", "Italiya", "Kanada", "Salvador"], answer: 0 },
    { flag: "🇿🇲", country: "Zambiya", options: ["Tayvan", "Efiopiya", "Qozog'iston", "Zambiya"], answer: 3 },
    { flag: "🇿🇼", country: "Zimbabve", options: ["Janubiy Koreya", "Tunis", "Zimbabve", "Islandiya"], answer: 2 }
  ],
  anagrams: [
    { word: "KITOB" },
    { word: "QALAM" },
    { word: "TELEGRAM" },
    { word: "FUTBOL" },
    { word: "SAMARQAND" },
    { word: "DASTURCHI" },
    { word: "ZUKKO" },
    { word: "MAKTAB" },
    { word: "DARAXT" },
    { word: "KOMPYUTER" },
    { word: "TELEFON" },
    { word: "MASHINA" },
    { word: "OFTOB" },
    { word: "YULDUZ" },
    { word: "KITOBXON" },
    { word: "SHAHAR" },
    { word: "QISHLOQ" },
    { word: "BOZOR" },
    { word: "RESTORAN" },
    { word: "UNIVERSITET" },
    { word: "TASHKENT" },
    { word: "NAMANGAN" },
    { word: "DOSTLIK" },
    { word: "OILA" },
    { word: "OSHXONA" }
  ]
};
